### ISSUE TITLE
Exam 4 Question 1

### ISSUE THREAD

**Issue by SaifeddineBarkia** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#114]
A developer needs to set up an SSL security certificate for a client's eCommerce website in order to use the HTTPS protocol. Which of the following AWS services can be used to deploy the required SSL server certificates? (Choose TWO)

A. Amazon Route 53.
B. AWS ACM.
C. AWS Directory Service.
D. AWS Identity & Access Management.
E. AWS Data Pipeline.

Should be A B

**Comment by kananinirav** [comment]
Thanks for the correction.
