### ISSUE TITLE
Exam 4 Qs 6

### ISSUE THREAD

**Issue by SaifeddineBarkia** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#115]
A customer is planning to move billions of images and videos to be stored on Amazon S3. The customer has approximately 60 Petabytes of data to move. Which of the following AWS Services is the best choice to transfer the data to AWS?

A. Snowball.
B. S3 Transfer Acceleration.
C. Snowmobile.
D. Amazon VPC.

Should be C

**Comment by kananinirav** [comment]
Thanks for the correction.
