### ISSUE TITLE
Exam 5 QS20

### ISSUE THREAD

**Issue by SaifeddineBarkia** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#118]
Which of the following is a feature of Amazon RDS that performs automatic failover when the primary database fails to respond?

A. RDS Single-AZ.
B. RDS Write Replica.
C. RDS Snapshots.
D. RDS Multi-AZ.

Should be D

**Comment by kananinirav** [comment]
Thanks for the correction.
