### ISSUE TITLE
Exam 7 Qs 36

### ISSUE THREAD

**Issue by SaifeddineBarkia** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#122]
A. AWS Lambda runs code without provisioning or managing servers.
B. AWS Lambda provides resizable compute capacity in the cloud.
C. There is no charge when your AWS Lambda code is not running.
D. AWS Lambda can be called directly from any mobile app.

Should be D

**Comment by kananinirav** [comment]
Thanks for the correction.
