### ISSUE TITLE
Hi, is this updated for clf-c02 ? 

### ISSUE THREAD

**Issue by theagilecoder** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#129]
AWS certified cloud practitioner exam has received an update from clf-c01 to clf-c02. Do these notes include the changes ? 

(Incredibly thankful for the work)

**Comment by kananinirav** [comment]
@theagilecoder 
I don't think there are many significant changes in the CLF-C02 exam. If you have a list of topics that are missing, I'll do my best to include them. I believe it covers all the changes.

You can find more information here: https://tutorialsdojo.com/new-aws-certified-cloud-practitioner-clf-c02-exam-version-in-2023/

**Comment by theagilecoder** [comment]
Thanks !
