### ISSUE TITLE
Practice exam 12 and Q#40

### ISSUE THREAD

**Issue by PMBABU108** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#160]
Dear Author,

Just wanted to let you know that the answer to the question #40 in #practice-exam-12 is not correct. It should be "D" as opposed to "B". Here is what I found.

"AWS Shield
AWS Shield is a managed distributed denial of service (DDoS) protection service that safeguards applications running on AWS. It provides dynamic detection and automatic inline mitigations that minimize application downtime and latency, so there is no need to engage AWS Support to benefit from DDoS protection."

Thanks & Best Regards,
Madhu

**Comment by kananinirav** [comment]
@PMBABU108 Thanks 🙏 🙇‍♂️
