### ISSUE TITLE
Two answers for Exam 9 Question 6

### ISSUE THREAD

**Issue by alexandroivaldez** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#161]
Practice Exam 9 asks "Which AWS service allows companies to connect an Amazon VPC to an on-premises data center?". The correct answer is listed as D. Amazon Direct Connect, however A. AWS VPN is also a correct answer.

**Comment by 12mse1113** [comment]
I got the same question on my exam today and It was a multiple choice

**Comment by kananinirav** [comment]
Thanks @alexandroivaldez @12mse1113 🙏 🙇
