### ISSUE TITLE
Exam 17 Question 5

### ISSUE THREAD

**Issue by nmzaheer** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#164]
Correct Answer : B

https://docs.aws.amazon.com/awssupport/latest/user/security-checks.html#security-groups-specific-ports-unrestricted

**Comment by nmzaheer** [comment]
Question 5 overlaps with Question 34 of the same test where the correct answer is mentioned.

**Comment by lukaevet** [comment]
Agree

**Comment by kananinirav** [comment]
Thanks @nmzaheer fixed with https://github.com/kananinirav/AWS-Certified-Cloud-Practitioner-Notes/pull/165 PR
