### ISSUE TITLE
Exam 4 question 36

### ISSUE THREAD

**Issue by cnjohnniekwok** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#169]
The answer should be:
D. AWS Pricing Calculator

I don't think there's a AWS TCO Calculator. and the link below said Pricing calculator is the TCO tool.
https://docs.aws.amazon.com/whitepapers/latest/how-aws-pricing-works/aws-pricingtco-tools.html

**Comment by kananinirav** [comment]
I think AWS TCO ss correct. 
Reference: https://stackoverflow.com/questions/63225305/difference-between-various-cost-estimation-tools-in-aws
