### ISSUE TITLE
Exam 23 Question 4

### ISSUE THREAD

**Issue by cnjohnniekwok** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#170]
Simple Monthly Calculator has retired on 23rd Mar 2023.
https://aws.amazon.com/blogs/aws-cloud-financial-management/la-time-to-say-goodbye-to-the-simple-monthly-calculator/

The answer should be AWS Pricing Calculator.

**Comment by kananinirav** [comment]
@cnjohnniekwok Thanks 🙇 🙏 🚀
