### ISSUE TITLE
Correct the option 

### ISSUE THREAD

**Issue by Anshul02092003** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#178]
On practice paper - 2, Question No. 12,  option C, which is the answer of the question, it should be - 

penetration testing of EC2 instances is only allowed with prior written approval from AWS

The change has to be - (with in place of without)

**Comment by kananinirav** [comment]
we can do penetration testing of EC2 without approval.  please check below link ⬇️ ⬇️ ⬇️ 

**Reference**: https://aws.amazon.com/security/penetration-testing/
