### ISSUE TITLE
Exam 16 Question 28

### ISSUE THREAD

**Issue by conti748** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#180]
What is an advantage of using the AWS Cloud over a traditional on-premises solution?

A. Users do not have to guess about future capacity needs.
B. Users can utilize existing hardware contracts for purchases.
C. Users can fix costs no matter what their traffic is.
D. Users can avoid audits by using reports from AWS.

Your correct answer is AC, but you do not write to select 2 options..
But, actually, I think C is wrong, the answer should be A

**Comment by kananinirav** [comment]
@conti748 Thanks. Fixed with https://github.com/kananinirav/AWS-Certified-Cloud-Practitioner-Notes/commit/117c48838dc4a225affac3977e915c2b4df6a921
