### ISSUE TITLE
Exam 17 question 44

### ISSUE THREAD

**Issue by kalel552** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#182]
The answers for this question are wrong. I took the AWS Skill Builder example exam and this question popped up there - the correct answers are A and C.

**Comment by kananinirav** [comment]
@kalel552 Thanks. Fixed with https://github.com/kananinirav/AWS-Certified-Cloud-Practitioner-Notes/commit/117c48838dc4a225affac3977e915c2b4df6a921
