### ISSUE TITLE
Incorrect Answer

### ISSUE THREAD

**Issue by mametur** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#185]
What are the benefits of using the Amazon Relational Database Service? (Choose TWO)

A. Lower administrative burden.
B. Complete control over the underlying host.
C. Resizable compute capacity.
D. Scales automatically to larger or smaller instance types.
E. Supports the document and key-value data structure.

Should be  A and D

Option C (Resizable compute capacity) is incorrect because while Amazon RDS allows users to resize their database instances, it does not specifically provide resizable compute capacity. Instead, users select predefined instance types with specific compute and memory configurations.

Question 35

https://github.com/kananinirav/AWS-Certified-Cloud-Practitioner-Notes/blob/master/practice-exam/practice-exam-3.md

**Comment by kalel552** [comment]
RDS doesn't automatically scale to larger or smaller instance types. You would have to create some custom logic for that.

**Comment by kananinirav** [comment]
@kalel552 💯

**Comment by kananinirav** [comment]
@mametur Correct answer is A and C
