### ISSUE TITLE
EXAM 4 - QUESTION

### ISSUE THREAD

**Issue by mametur** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#193]
A company needs to migrate their website from on-premises to AWS. Security is a major concern for them, so they need to host their website on hardware that is NOT shared with other AWS customers. Which of the following EC2 instance options meets this requirement?

A. On-demand instances.
B. Spot instances.
C. Dedicated instances.
D. Reserved instances

The given answer is C ;

**It should be Dedicated host**

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/dedicated-instance.html

**Comment by kananinirav** [comment]
@mametur 

They are physically isolated at the host hardware level from instances that belong to other AWS accounts but might share hardware with other instances from the same account. 

Dedicated host: Can share instance capacity with other accounts.

So option C is correct.
