### ISSUE TITLE
Exam 20 Question 34

### ISSUE THREAD

**Issue by AkaCoder404** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#195]
```
34. Who is responsible for patching the guest operating system for Amazon RDS?

A. The AWS Product team
B. The customer Database Administrator
C. Managed partners
D. AWS Support
```

RDS is fully managed. Shouldn't the answer be A instead of B.

**Comment by kananinirav** [comment]
@AkaCoder404 [According to AWS’s Shared Responsibility Model, while AWS is responsible for patching and fixing flaws within the infrastructure, customers are responsible for patching their guest OS and applications](https://aws.amazon.com/compliance/shared-responsibility-model/)

B is correct answer
