### ISSUE TITLE
Exam 17 -Question 27

### ISSUE THREAD

**Issue by tsasse17** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#209]

**Comment by javierspn** [comment]
Exam 17 Question 27 has the wrong answers, it is A and B

Which services use AWS edge locations? (Choose two.)

    A. Amazon CloudFront
    B. AWS Shield
    C. Amazon EC2
    D. Amazon RDS
    E. Amazon ElastiCache

Answer: A, C
Correct Answer: A, B
