### ISSUE TITLE
Exam 10 and Exam 14 Question 45

### ISSUE THREAD

**Issue by holopekochan** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#214]
Exam 10 and Exam 14 Question 45
Same question, but different answer 

Amazon Relational Database Service (Amazon RDS) offers which of the following benefits over traditional database management?
A. AWS manages the data stored in Amazon RDS tables.
B. AWS manages the maintenance of the operating system.
C. AWS automatically scales up instance types on demand.
D. AWS manages the database type.

Practice 10 says C
Practice 14 says B

**Comment by Elamouri** [comment]
Practice 10 is correct, as option C ("AWS automatically scales up instance types on demand") is a benefit offered by Amazon RDS.
Practice 14 is incorrect, as option B ("AWS manages the maintenance of the operating system") is not a direct benefit offered by Amazon RDS.

**Comment by furqann** [comment]
The correct option should be option B _AWS manages the maintenance of the operating system
Because AWS does not scale up instance types on-demand, unless you have enabled auto-scaling. Even when the autoscaling is turned on, aws rds only scale-up the storage.
