### ISSUE TITLE
Exam 1 - Question 8

### ISSUE THREAD

**Issue by Elamouri** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#215]
What does AWS Snowball provide? (Choose TWO)

A. Built-in computing capabilities that allow customers to process data locally.
B. A catalog of third-party software solutions that customers need to build solutions and run their businesses.
C. A hybrid cloud storage between on-premises environments and the AWS Cloud.
D. An Exabyte-scale data transfer service that allows you to move extremely large amounts of data to AWS.
E. Secure transfer of large amounts of data into and out of the AWS.

Answer :  D & E

- D)AWS Snowball is designed specifically for large-scale data transfers, including exabyte-scale data. It offers a physical device that customers can use to transfer petabytes of data securely to and from AWS, bypassing the limitations of internet bandwidth and ensuring faster data transfer.

- E)Security is a critical aspect of AWS Snowball. It provides secure encryption of data during transit, ensuring that large amounts of data can be transferred into and out of the AWS cloud securely. This encryption helps safeguard sensitive data during the transfer process, providing peace of mind to customers concerned about the security of their data.
-----------------------------------------------------------------------------------------------------------------------------
Not A because :
AWS Snowball primarily focuses on data transfer rather than processing data locally. While it does have limited compute capabilities for tasks like encryption and data validation, it's not designed for extensive data processing.

**Comment by andrew-aiken** [comment]
**A** is correct, snowball can run workloads locally on them (gpu, lambda, clustering) https://aws.amazon.com/snowball/features/


**D** is incorrect because they cannot store that scale of data.

Storage optimized:
> Snowball Edge Storage Optimized provides 80TB HDD or 210TB NVMe capacity for Amazon S3-compatible object storage

**Comment by kananinirav** [comment]
@andrew-aiken I Agree with you. A, E is correct

**Comment by Senam-Kudjo** [comment]
It's A & E because Snowball doesn't deal with Exabyte-scale data transfer that's rather Snowmobile
