### ISSUE TITLE
Amendments to questions in Practice Exam 21

### ISSUE THREAD

**Issue by rebeus** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#228]
```
11. A company wants to use Amazon Elastic Compute Cloud (Amazon EC2) to deploy a global commercial application. The deployment solution should be built with the highest redundancy and fault tolerance. <br/> Based on this situation, the Amazon EC2 instances should be deployed:
    - A. in a single Availability Zone in one AWS Region
    - B. with multiple Elastic Network Interfaces belonging to different subnets
    - C. across multiple Availability Zones in one AWS Region
    - D. across multiple Availability Zones in two AWS Regions

    <details markdown=1><summary markdown="span">Answer</summary>

    Correct Answer: C

    Explanation: <https://jayendrapatil.com/aws-high-availability-fault-tolerance-architecture-certification/>

    </details>
```
It should be `Correct Answer: D`
Reason: It's referring to _"..highest redundancy and fault tolerance"_.  If you've only deployed your app/service in multiple A-Z's in one region (Option C) but the region goes down then you won't be able to serve your clients/customers which is not what we want. Deploying across multiple Availability Zones in two AWS Regions (Option D) helps with redundancy, fault tolerance and resiliency. 

```
29. How can a company separate costs for network traffic, Amazon EC2, Amazon S3, and other AWS services by department?
    - A. Add department-specific tags to each resource
    - B. Create a separate VPC for each department
    - C. Create a separate AWS account for each department
    - D. Use AWS Organizations

    <details markdown=1><summary markdown="span">Answer</summary>

    Correct Answer: A

    Explanation: <https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/custom-tags.html#allocation-how>

    </details>
```
Shouldn't it be : `Correct Answer: C`
This is because that will allow you to exactly separate the costs by department.

```
50. Fault tolerance refers to:
    - A. the ability of an application to accommodate growth without changing design
    - B. how well and how quickly an application's environment can have lost data restored
    - C. how secure your application is
    - D. the built-in redundancy of an application's components

    <details markdown=1><summary markdown="span">Answer</summary>

    Correct Answer: D

    </details>
```
Is option `D.the built-in redundancy of an application's components` correct?

**Comment by rebeus** [comment]
Currently in draft. if i find further corrections required in Practice Exam 21, I will raise them within this issue item.

**Comment by rebeus** [comment]
@kananinirav @alessiobennardo @StefH @pescap - can one of you review the above please and confirm whether or not what I am proposing is correct?

**Comment by pescap** [comment]
Hi, I can add a few remarks. According to [this answer in Brainly](https://brainly.com/question/40860964?source=regflowPage&cb=1717246868846), the correct answer to 11 is C:

```
Deploying the instances across multiple AWS Regions would provide even greater 
redundancy and fault tolerance, but it may also introduce additional latency due 
to the longer distance between regions. 
It is a trade-off between increased resilience and potential performance impact.
```

I agree with you that this trade-off argument might feel subjective. It sounds like the performance degradation with multiple AWS Regions is too high in practice.

29: I would agree with you.
50: I would also agree with you.

**Comment by rebeus** [comment]
Hi @pescap  so are we going to still go with answer C for question 11.

Regarding the questions 29 and 50 can those be reviewed and corrected? @kananinirav @pescap @StefH @alessiobennardo

**Comment by kananinirav** [comment]
@rebeus 

question 11, C is correct, agree with @pescap 
question 29, C is correct 
question 50, D is correct
