### ISSUE TITLE
Same question in different exams with different answers

### ISSUE THREAD

**Issue by LiorA1** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#236]
In the below link, there is the same question, with different correct answer.
Can we fix it?
```
1. Which services can be used across hybrid AWS Cloud architectures? (Select TWO.)
    - A. Amazon Route 53
    - B. Virtual Private Gateway
    - C. Classic Load Balancer
    - D. Auto Scaling
    - E. Amazon CloudWatch default metrics

    <details markdown=1><summary markdown="span">Answer</summary>

    Correct Answer: AE

    Explanation:
    - <https://aws.amazon.com/cloudwatch/>
    - You can also use CloudWatch in hybrid cloud architectures by using the CloudWatch Agent or API to monitor your on-premises resources

    </details>
``` 
https://github.com/kananinirav/AWS-Certified-Cloud-Practitioner-Notes/blob/master/practice-exam/practice-exam-13.md?plain=1#L156

```
43. Which services can be used across hybrid AWS Cloud architectures? (Select TWO)
    - A. Amazon Route 53.
    - B. Virtual Private Gateway.
    - C. Classic Load Balancer.
    - D. Auto Scaling.
    - E. Amazon CloudWatch default metrics.

    <details markdown=1><summary markdown='span'>Answer</summary>
      Correct answer: A, B
    </details>
```
https://github.com/kananinirav/AWS-Certified-Cloud-Practitioner-Notes/blob/master/practice-exam/practice-exam-9.md?plain=1#L442

**Comment by ProttoySarker** [comment]
The correct answers to this question are A and B. This is because AWS CloudWatch default metrics only measure metrics on AWS resources, not on On-Premises resources.

**Comment by kananinirav** [comment]
@LiorA1 Thanks I will update it. 🙏

**Comment by kananinirav** [comment]
https://github.com/kananinirav/AWS-Certified-Cloud-Practitioner-Notes/commit/dbfc6f748c372d35ab319d832ae74ac96c4b267f
