### ISSUE TITLE
Exam 20: Quest 15

### ISSUE THREAD

**Issue by hsunmr** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#238]
15. Each department within a company has its own independent AWS account and its own payment method. New company leadership wants to centralize departmental governance and consolidate payments.
How can this be achieved using AWS services or features?

- A. Forward monthly invoices for each account. Then create IAM roles to allow cross-account access.
- B. Create a new AWS account. Then configure AWS Organizations and invite all existing accounts to join.
- C. Configure AWS Organizations in each of the existing accounts. Then link all accounts together.
- D. Use Cost Explorer to combine costs from all accounts. Then replicate IAM policies across accounts.

Original Answer: C

The correct answer is `B`

**Comment by hsunmr** [comment]
AWS Organizations is a service designed to help you centrally manage and govern your environment as you grow and scale your AWS resources. By creating a new AWS account and configuring AWS Organizations, you can invite all existing departmental accounts to join the organization.

not configure each of existing accounts

**Comment by kananinirav** [comment]
@hsunmr You are correct. B is the correct answer. I will update it 🙏

**Comment by kananinirav** [comment]
https://github.com/kananinirav/AWS-Certified-Cloud-Practitioner-Notes/commit/dbfc6f748c372d35ab319d832ae74ac96c4b267f
