### ISSUE TITLE
Practice exam 10 Question Question no: 44

### ISSUE THREAD

**Issue by Kathireshpraveen** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#247]
The answer for practice exam 10 Q44 is wrong. The answer would be AutoScaling

**Comment by kananinirav** [comment]
@Kathireshpraveen Thanks I will update it. 🙇

**Comment by kananinirav** [comment]
https://github.com/kananinirav/AWS-Certified-Cloud-Practitioner-Notes/commit/dbfc6f748c372d35ab319d832ae74ac96c4b267f
