### ISSUE TITLE
Practice Exam 2 amendment required

### ISSUE THREAD

**Issue by rebeus** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#248]
```
What are two advantages of using Cloud Computing over using traditional data centers? (Choose TWO)

A. Reserved Compute capacity.
B. Eliminating Single Points of Failure (SPOFs).
C. Distributed infrastructure.
D. Virtualized compute resources.
E. Dedicated hosting.
Answer
Correct answer: C, D
```

I've found conflicting answers regarding the above.
Some say it should be
- Eliminating Single Points of Failure (SPOFs).
- Distributed infrastructure.

Therefore **B+C** in this case

**Comment by rebeus** [comment]
@kananinirav any chance this can be reviewed and updated please?

**Comment by kananinirav** [comment]
@rebeus I think D is also correct but the best choices are B And C ✅ I will update it.

**Comment by kananinirav** [comment]
https://github.com/kananinirav/AWS-Certified-Cloud-Practitioner-Notes/commit/dbfc6f748c372d35ab319d832ae74ac96c4b267f
