### ISSUE TITLE
Practice Exam 3

### ISSUE THREAD

**Issue by ertejaspatel** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#72]
Which of the following common IT tasks can AWS cover to free up company IT resources? (Select TWO.)

A. Patching databases software
B. Testing application releases
C. Backing up databases
D. Creating database schema
E. Running penetration tests
Answer
Correct Answer: BE

It should be A & C

**Comment by kananinirav** [comment]
@ertejaspatel 
Thank you for bringing this to our attention. We apologize for any confusion this may have caused. We have reviewed Practice Exam and made any necessary corrections to ensure the accuracy of our content. If you have any further questions or concerns, please feel free to reach out to us.
