### ISSUE TITLE
Practice Exam 11 Q15

### ISSUE THREAD

**Issue by ertejaspatel** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#73]
Which AWS Trusted Advisor check is available to all AWS users?

A. Core checks
B. All checks
C. Cost optimization checks
D. Fault tolerance checks
Answer
Correct Answer: C

It should be A
https://aws.amazon.com/premiumsupport/technology/trusted-advisor/

**Comment by kananinirav** [comment]
@ertejaspatel 
Thank you for bringing this to our attention. We apologize for any confusion this may have caused. We have reviewed Practice Exam and made any necessary corrections to ensure the accuracy of our content. If you have any further questions or concerns, please feel free to reach out to us.
