### ISSUE TITLE
Practice Exam 4 Q4

### ISSUE THREAD

**Issue by KhaledTaymour** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#74]
I think answer should be A. Amazon CloudFront

**Comment by kananinirav** [comment]
hi, @KhaledTaymour 

Thank you for bringing this to our attention. We apologize for any confusion this may have caused. We have reviewed Practice Exam and made any necessary corrections to ensure the accuracy of our content. If you have any further questions or concerns, please feel free to reach out to us. Good luck with your Cloud Practitioner studies!

**Comment by KhaledTaymour** [comment]
Hi @kananinirav,

You are welcome, I really appreciate your effort gathering all these questions 🙏.
