### ISSUE TITLE
Practice Exam 4 Q38

### ISSUE THREAD

**Issue by ponakalaneha** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#79]
![image](https://github.com/kananinirav/AWS-Certified-Cloud-Practitioner-Notes/assets/58983519/f8046172-49ae-4cf4-93c2-2ce18ddb6275)

The question asking to choose 2 option, there is only one option mentioned and the option is also wrong about the moving of customers to AWS .

The correct answer: C , E

**Comment by kananinirav** [comment]
@ponakalaneha 

Thank you for pointing out. We apologize for the mistake and will correct it. Your feedback is much appreciated!😊
